### ISSUE TITLE
Issues mentioned

### ISSUE THREAD

**Issue by shujaatbidar** [cp317/angular-frontend#4]
Some issues Mr. Brown mentioned today:

- Put a timer on the beacon with a start and end timer.
- allow to see future beacons, so people don’t get confused if the beacon starts in 6 hours from now or in 2 weeks.
- have same layout (fonts) etc if possible.
- fix any white spaces
- longitude and latitude, change to about 5-6 decimal place for the location.

**Comment by Amandeep-G** [comment]
Changed longitude and latitude to 5 decimal places (+/- 10 meters of accuracy)

**Comment by GarethSharpe** [comment]
- Beacon cards display start time
- User could always see future beacons
- Minimal white space
- Also added a join/leave toggle so users know when they have interacted with a beacon card
